# Generated by Django 2.1.8 on 2020-03-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='is_not',
            new_name='is_hot',
        ),
    ]
